### ISSUE TITLE
Error : The PEAR repository has been removed from Composer 2.0

### ISSUE THREAD

**Issue by dr1361teh** [vatsimnetwork/osticket-auth-vatsim#1]
Hello,

After running " php make.php hydrate ", I got the following error:

The PEAR repository has been removed from Composer 2.0

What should I do to solve this problem ?

**Comment by amosngSP** [comment]
Hi @dr1361teh 
For me i resolved the problem by manually installing the required components through composer.
First do
`apt install composer`
Change directory to the vatsim plugin folder and type in
`composer install`
Then try running
`php make.php hydrate`
Again

**Comment by dr1361teh** [comment]
Hi @amosngSP 
Thx for your instruction.
I did your suggestion but it shows the same error:

```
# composer install
The PEAR repository has been removed from Composer 2.x
```
What is your composer version ? Mine is  2.1.8

**Comment by amosngSP** [comment]
> Hi @amosngSP Thx for your instruction. I did your suggestion but it shows the same error:
> 
> ```
> # composer install
> The PEAR repository has been removed from Composer 2.x
> ```
> 
> What is your composer version ? Mine is 2.1.8

Forgot what composer version I used when deploying osticket, but it should just be a general warning.  I received it too, try installing the plugin in your osticket panel?

**Comment by dr1361teh** [comment]
> 
> 
> > Hi @amosngSP Thx for your instruction. I did your suggestion but it shows the same error:
> > ```
> > # composer install
> > The PEAR repository has been removed from Composer 2.x
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What is your composer version ? Mine is 2.1.8
> 
> Forgot what composer version I used when deploying osticket, but it should just be a general warning. I received it too, try installing the plugin in your osticket panel?

Yes, of course I installed it. But when I click on "Sign in with VATSIM" button, it just open a blank white page !!! .htaccess instruction doesn't help ! 
Did you face with this issue ?
